# Generated by Django 4.2 on 2023-05-15 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='closet',
            name='classification',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
