# Generated by Django 4.2 on 2023-05-17 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('closet', '0002_closet_classification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='closet',
            name='classification',
        ),
    ]
