# Generated by Django 4.2 on 2023-05-11 17:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0002_remove_photo_image_remove_photo_post_photo_imagedata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='like_users',
            field=models.ManyToManyField(related_name='like_photos', to=settings.AUTH_USER_MODEL),
        ),
    ]
