# Generated by Django 4.2 on 2023-05-17 16:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0003_photo_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='like_users',
        ),
        migrations.AddField(
            model_name='photo',
            name='like',
            field=models.ManyToManyField(blank=True, related_name='like_imgfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
