# Generated by Django 4.2 on 2023-05-17 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_photo_like_users_photo_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='already_like',
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name='photo',
            name='like',
        ),
        migrations.AddField(
            model_name='photo',
            name='like',
            field=models.TextField(default='<i class="far fa-heart"></i> '),
        ),
    ]
